#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ND Capital — data feed generator (Agent F3, Website Publisher).

Builds the three JSON feeds that are NOT produced by write_research.py:

    website/data/brief.json      latest morning brief, from website/content/briefs/*.md
    website/data/bets.json       the prediction record, from the scorecard + coverage book
    website/data/earnings.json   forward earnings calendar + our earnings-risk scores

    python website/write_feeds.py

Design rules, enforced here rather than trusted to a human:

  * Nothing is invented. A field we do not have is null, with a `_missing` note
    explaining why. Placeholders are never dressed up as data.
  * Rows in the scorecard flagged as EXAMPLE / template are excluded from the
    published record. They exist to document the schema, not to pad a track record.
  * The coverage book is the live prediction record until the scorecard is
    populated: 24 dated, falsifiable calls with targets and review dates.
  * Losses are published on the same footing as wins. There is no filter that
    could remove them, by construction.

`coverage.json` and `themes.json` are generated by write_research.py / write_themes.py
and are deliberately not touched by this script.
"""

import json
import os
import re
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(HERE, "data")
BRIEFS = os.path.join(HERE, "content", "briefs")
SCORECARD = os.path.join(ROOT, "Research", "_Knowledge-Base", "Scorecards", "predictions.xlsx")

TODAY = datetime.now().strftime("%Y-%m-%d")

# Forward earnings dates confirmed against the Alpha Vantage EARNINGS_CALENDAR
# endpoint on 2026-08-03. The free plan is capped at 25 requests/day and the cap
# was reached part-way through the coverage sweep, so the remaining names carry a
# null date rather than an estimate. An estimated date presented as a confirmed
# one is exactly the kind of quiet fabrication this file exists to prevent.
EARNINGS_CONFIRMED = {
    "NVDA":  {"date": "2026-08-26", "fiscal_end": "2026-07-31", "eps_estimate": 2.01, "time": "post-market"},
    "AMD":   {"date": "2026-08-04", "fiscal_end": "2026-06-30", "eps_estimate": 1.35, "time": "post-market"},
    "AVGO":  {"date": "2026-09-03", "fiscal_end": "2026-07-31", "eps_estimate": 2.83, "time": None},
    "GOOGL": {"date": "2026-10-28", "fiscal_end": "2026-09-30", "eps_estimate": 3.02, "time": None},
}
# Queried and returned no scheduled event inside the 3-month window (already reported).
EARNINGS_NONE_SCHEDULED = ["AAPL", "META"]
EARNINGS_SOURCE = "Alpha Vantage EARNINGS_CALENDAR, queried 2026-08-03"


def load(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as fh:
        return json.load(fh)


def save(name, obj):
    path = os.path.join(DATA, name)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(obj, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print(f"  wrote data/{name}")


def front_matter(text):
    """Minimal YAML front-matter reader — same subset build.py/md.py accept."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    raw, body = text[3:end], text[end + 4:]
    meta = {}
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        k, v = line.split(":", 1)
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            v = [x.strip().strip("'\"") for x in v[1:-1].split(",") if x.strip()]
        else:
            v = v.strip("'\"")
        meta[k.strip()] = v
    return meta, body.lstrip("\n")


# ---------------------------------------------------------------- brief.json

def build_brief():
    files = sorted(f for f in os.listdir(BRIEFS) if f.endswith(".md")) if os.path.isdir(BRIEFS) else []
    if not files:
        return save("brief.json", {
            "updated_at": TODAY, "status": "none_published", "latest": None,
            "_missing": "No brief files in website/content/briefs/.",
        })

    slug = os.path.splitext(files[-1])[0]
    with open(os.path.join(BRIEFS, files[-1]), encoding="utf-8") as fh:
        meta, body = front_matter(fh.read())

    # Section headings double as the at-a-glance summary of what the brief covers.
    headings = re.findall(r"^##\s+(.+?)\s*$", body, re.M)

    save("brief.json", {
        "updated_at": TODAY,
        "status": "published",
        "latest": {
            "date": str(meta.get("date", slug))[:10],
            "slug": slug,
            "url": f"briefs/{slug}.html",
            "title": meta.get("title"),
            "standfirst": meta.get("standfirst"),
            "sections": headings,
            "tickers": meta.get("tickers") or [],
            "tags": meta.get("tags") or [],
        },
        "archive_count": len(files),
        "archive": [{"date": os.path.splitext(f)[0], "url": f"briefs/{os.path.splitext(f)[0]}.html"}
                    for f in reversed(files)],
        "cadence": "Every trading morning, before the US open.",
        "disclaimer": "Research and education, not investment advice.",
    })


# ---------------------------------------------------------------- bets.json

def read_scorecard():
    """Return (real_rows, excluded_rows). Excluded = template/example rows."""
    try:
        import openpyxl
    except ImportError:
        return None, None
    if not os.path.isfile(SCORECARD):
        return None, None

    wb = openpyxl.load_workbook(SCORECARD, data_only=True)
    ws = wb["Predictions"]
    rows = list(ws.iter_rows(values_only=True))
    header_i = next((i for i, r in enumerate(rows) if r and r[0] == "ID"), None)
    if header_i is None:
        return [], []

    cols = [str(c).strip() if c else "" for c in rows[header_i]]
    real, excluded = [], []
    for r in rows[header_i + 1:]:
        if not r or not r[0]:
            continue
        rec = {cols[i]: r[i] for i in range(len(cols)) if cols[i]}
        blob = " ".join(str(v) for v in rec.values() if v is not None).upper()
        # A row that announces itself as an example is documentation, not a call.
        if "EXAMPLE" in blob or str(rec.get("Ticker / theme", "")).upper() in ("EXMPL", "EXAMPLE", "TICKER"):
            excluded.append(rec)
        else:
            real.append(rec)
    return real, excluded


def build_bets(cov):
    real, excluded = read_scorecard()
    cs = cov["companies"]

    # The coverage book IS the live prediction record: every entry is a dated,
    # falsifiable call with a target, a conviction level and a review date.
    open_calls = [{
        "id": f"COV-{c['ticker']}",
        "date_made": c.get("last_review"),
        "ticker": c["ticker"],
        "company": c["name"],
        "type": "Rating + target price",
        "claim": c.get("one_liner"),
        "direction": {"Overweight": "Long", "Underweight": "Short/Avoid"}.get(c["rating"], "Neutral"),
        "rating": c["rating"],
        "price_at_call": c.get("price"),
        "target": c.get("target"),
        "implied_upside": c.get("upside"),
        "conviction": c.get("conviction"),
        "earnings_risk": c.get("earnings_risk"),
        "horizon": "~12 months",
        "evaluation_date": "2026-11-01",
        "status": "Open",
        "outcome": None,
        "reasoning_quality": None,
        "url": f"coverage/{c['ticker']}.html",
    } for c in cs]

    by_rating = {r: len([c for c in cs if c["rating"] == r])
                 for r in ("Overweight", "Neutral", "Underweight")}
    by_conviction = {k: len([c for c in cs if c.get("conviction") == k])
                     for k in ("High", "Medium", "Low")}

    save("bets.json", {
        "updated_at": TODAY,
        "coverage_initiated": cov.get("as_of"),
        "summary": {
            "open_calls": len(open_calls),
            "resolved": 0,
            "correct": 0,
            "partial": 0,
            "wrong": 0,
            "hit_rate": None,
            "high_conviction_hit_rate": None,
            "calibration": None,
            "avg_return_per_call": None,
            "since_inception": None,
            "_missing": (
                "No call has reached its evaluation date. The first scheduled review is "
                "1 November 2026. Hit rate, calibration and average return are null because "
                "they are not yet computable — not because they are being withheld."
            ),
        },
        "distribution": {"by_rating": by_rating, "by_conviction": by_conviction},
        "open_calls": open_calls,
        "resolved_calls": [],
        "losses": [],
        "_losses_note": (
            "Empty because nothing has resolved yet, not because losses are filtered. "
            "Resolved calls are published here in full, wins and losses on the same footing."
        ),
        "scorecard": {
            "source": "Research/_Knowledge-Base/Scorecards/predictions.xlsx",
            "logged_predictions": len(real) if real is not None else None,
            "excluded_template_rows": len(excluded) if excluded is not None else None,
            "_note": (
                "The scorecard workbook currently holds only its EXAMPLE schema row, which is "
                "excluded from everything published here. The 24 coverage calls above are the "
                "live record and are not yet mirrored into the workbook — flagged to Agent F1 "
                "ahead of the first performance review."
            ) if (real is not None and not real) else None,
        },
        "scoring_method": {
            "axes": ["Outcome (Correct / Partial / Wrong)", "Reasoning quality (Sound / Flawed / Lucky)"],
            "principle": "A right answer from flawed reasoning is recorded as a failure, because it will not repeat.",
            "calibration": "Stated scenario probabilities are tested against realised frequencies.",
            "conviction_test": "High-conviction calls must beat the overall hit rate or the label carries no information.",
            "revisions": "Prior views are never deleted. Every change is logged with its date and reason.",
            "explainer": "insights/scoring-your-own-calls.html",
        },
        "disclaimer": "Research and education, not investment advice. Past performance is not indicative of future results.",
    })


# ---------------------------------------------------------------- earnings.json

def build_earnings(cov):
    cs = {c["ticker"]: c for c in cov["companies"]}
    upcoming, unscheduled, unknown = [], [], []

    for tk, c in cs.items():
        # Earnings-risk score is OUR judgement, from the completed deep dive.
        # The date is vendor data. They are sourced separately and labelled separately.
        row = {
            "ticker": tk,
            "company": c["name"],
            "our_earnings_risk": c.get("earnings_risk"),
            "our_rating": c["rating"],
            "conviction": c.get("conviction"),
            "url": f"coverage/{tk}.html",
        }
        if tk in EARNINGS_CONFIRMED:
            e = EARNINGS_CONFIRMED[tk]
            row.update({
                "report_date": e["date"], "fiscal_period_end": e["fiscal_end"],
                "consensus_eps": e["eps_estimate"], "time_of_day": e["time"],
                "date_source": EARNINGS_SOURCE, "date_status": "Confirmed by vendor calendar",
            })
            upcoming.append(row)
        elif tk in EARNINGS_NONE_SCHEDULED:
            row.update({"report_date": None, "date_status": "No event scheduled in the next 3 months",
                        "date_source": EARNINGS_SOURCE})
            unscheduled.append(row)
        else:
            row.update({"report_date": None, "date_status": "Not confirmed — vendor daily request cap reached",
                        "date_source": None})
            unknown.append(row)

    upcoming.sort(key=lambda r: r["report_date"])

    save("earnings.json", {
        "updated_at": TODAY,
        "source": EARNINGS_SOURCE,
        "confirmed_count": len(upcoming),
        "unconfirmed_count": len(unknown),
        "upcoming": upcoming,
        "none_scheduled": unscheduled,
        "date_not_confirmed": unknown,
        "risk_scale": ["Low", "Medium", "High", "Very high"],
        "_risk_note": (
            "The earnings-risk score is our own judgement from the company deep dive — a read on "
            "how much the stock typically moves on results and how much is already priced in. It is "
            "not vendor data. Report dates are vendor data and are labelled with their status."
        ),
        "_coverage_note": (
            f"{len(unknown)} of {len(cs)} names carry no confirmed date. The market-data plan is "
            "capped at 25 requests a day and the cap was reached during the sweep. Estimated dates "
            "are not published as confirmed ones."
        ),
        "disclaimer": "Research and education, not investment advice.",
    })


def main():
    cov = load("coverage.json")
    print("Generating data feeds…")
    build_brief()
    build_bets(cov)
    build_earnings(cov)
    print("Done.")


if __name__ == "__main__":
    main()
